# Generated by Django 2.0.4 on 2018-04-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamps',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
