# Generated by Django 2.0.4 on 2018-04-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='city',
            field=models.CharField(default='Los Angeles', max_length=150),
            preserve_default=False,
        ),
    ]
